### ISSUE TITLE
`ImageFileProcessor.DownloadExecutableFiles();` throws `InvalidDataException`

### ISSUE THREAD

**Issue by SakulFlee** [askatmaster/MediaFileProcessor#3]
# Full exception:
```
Exception has occurred: CLR/System.IO.InvalidDataException
Exception thrown: 'System.IO.InvalidDataException' in System.Private.CoreLib.dll: 'Found invalid data while decoding.'
   at MediaFileProcessor.Processors.ZipFileProcessor.Open(Stream _stream, FileAccess _access, Boolean _leaveOpen)
   at MediaFileProcessor.Processors.ZipFileProcessor.Open(String _filename, FileAccess _access)
   at MediaFileProcessor.Processors.ImageFileProcessor.<DownloadExecutableFiles>d__21.MoveNext()
   at (...)
```

---

The issue seems to be related to `https://imagemagick.org/archive/binaries/ImageMagick-7.1.0-61-portable-Q16-x64.zip` (as mentioned in the README) no longer working and throwing a 404:
![image](https://github.com/askatmaster/MediaFileProcessor/assets/13678392/c1dd3ce5-b23a-4c86-9e5e-bd19437fa1b4)

**Comment by askatmaster** [comment]
Thank you will be fixed soon.

**Comment by askatmaster** [comment]
This issue is fixed. The file is downloaded correctly and the executable file is successfully extracted.
